artifacts_root : "artifacts"

data_ingestion:
    root_dir: "artifacts/data_ingestion"
    source_URL: "https://github.com/Joyeljames/dialogflow_chatbot/raw/refs/heads/main/data/brain_tumor_dataset.zip"
    local_data_file: "artifacts/data_ingestion/brain_tumor_dataset.zip"
    unzip_dir: "artifacts/data_ingestion"